dist: xenial
language: minimal
addons:
  apt:
    packages:
    - qemu
    - gdisk
    - dosfstools
    - e2fsprogs
    - pixz
    - grub-pc-bin
    - grub-efi-amd64-bin
env:
  global:
    - ALPINE_BRANCH="v3.9"
    - ALPINE_MIRROR="http://dl-cdn.alpinelinux.org/alpine"
    - ALPINE_PACKAGES="build-base ca-certificates ssl_client"
  matrix:
    - ARCH="x86_64"
    - ARCH="aarch64"
script:
  - sudo ./build.sh
