version: 2
jobs:
  build:
    machine: true
    environment:
      ALPINE_BRANCH: v3.9
      ALPINE_MIRROR: http://dl-cdn.alpinelinux.org/alpine
      ALPINE_PACKAGES: build-base ca-certificates ssl_client
    steps:
      - checkout
      - run:
          name: Git Submodules
          command: git submodule update --init --recursive
      - run:
          name: Creating Base Image - x86_64
          command: sudo ./alpine-chroot-install/alpine-chroot-install
          environment:
            ARCH: x86_64
            CHROOT_DIR: /alpine-x86_64
      - run:
          name: Creating Base Image - armhf
          command: sudo ./alpine-chroot-install/alpine-chroot-install
          environment:
            ARCH: armhf
            CHROOT_DIR: /alpine-armhf
      - run:
          name: Creating Base Image - aarch64
          command: sudo ./alpine-chroot-install/alpine-chroot-install
          environment:
            ARCH: aarch64
            CHROOT_DIR: /alpine-aarch64
