version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Git Submodules
          command: git submodule update --init --recursive
      - run:
          name: Install Required Packages
          command: |
            echo 'deb http://archive.ubuntu.com/ubuntu artful main universe' | sudo tee /etc/apt/sources.list.d/ubuntu-artful.list
            sudo apt-get -q update
            sudo DEBIAN_FRONTEND="noninteractive" DEBIAN_PRIORITY="critical" apt-get -q install -y --no-install-recommends --target-release artful qemu-user-static
            sudo DEBIAN_FRONTEND="noninteractive" DEBIAN_PRIORITY="critical" apt-get -q install -y --no-install-recommends qemu parted pixz
      - run:
          name: Creating Base Image - x86_64
          command: ARCH="x86_64" ./build.sh
      - run:
          name: Creating Base Image - armhf
          command: ARCH="armhf" ./build.sh
      - run:
          name: Creating Base Image - aarch64
          command: ARCH="aarch64" ./build.sh
