version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Git Submodules
          command: git submodule update --init --recursive
      - run:
          name: Install Required Packages
          command: |
            sudo apt-get -q update
            sudo DEBIAN_FRONTEND="noninteractive" DEBIAN_PRIORITY="critical" apt-get -q install -y --no-install-recommends qemu gdisk pixz grub2 grub-pc-bin grub-efi-amd64-bin
            echo 'deb http://archive.ubuntu.com/ubuntu artful main universe' | sudo tee /etc/apt/sources.list.d/ubuntu-artful.list
            sudo apt-get -q update
            sudo DEBIAN_FRONTEND="noninteractive" DEBIAN_PRIORITY="critical" apt-get -q install -y --no-install-recommends --target-release artful qemu-user-static
      - run:
          name: Creating Base Image - x86_64
          command: sudo ./build.sh -a x86_64
      - run:
          name: Creating Base Image - aarch64
          command: sudo ./build.sh -a aarch64
