version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Git Submodules
          command: git submodule update --init --recursive
      - run:
          name: Required Packages
          command: sudo apt-get install -y qemu-user-static
      - run:
          name: Creating Base Image - x86_64
          command: >-
            sudo
            ALPINE_BRANCH="v3.9"
            ALPINE_MIRROR="http://dl-cdn.alpinelinux.org/alpine"
            ALPINE_PACKAGES="build-base ca-certificates ssl_client"
            ARCH="x86_64"
            CHROOT_DIR="/alpine-x86_64"
            ./alpine-chroot-install/alpine-chroot-install
      - run:
          name: Creating Base Image - armhf
          command: >-
            sudo
            ALPINE_BRANCH="v3.9"
            ALPINE_MIRROR="http://dl-cdn.alpinelinux.org/alpine"
            ALPINE_PACKAGES="build-base ca-certificates ssl_client"
            ARCH="armhf"
            CHROOT_DIR="/alpine-armhf"
            ./alpine-chroot-install/alpine-chroot-install
      - run:
          name: Creating Base Image - aarch64
          command: >-
            sudo
            ALPINE_BRANCH="v3.9"
            ALPINE_MIRROR="http://dl-cdn.alpinelinux.org/alpine"
            ALPINE_PACKAGES="build-base ca-certificates ssl_client"
            ARCH="aarch64"
            CHROOT_DIR="/alpine-aarch64"
            ./alpine-chroot-install/alpine-chroot-install
